version: '3.9'
services:
  app:
    image: ghcr.io/shba007/untest-web:latest
    env_file:
      - .env.prod
    ports:
      - 4201:3000
    networks:
      - front-tier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

  postgres:
    image: postgres:17-alpine
    command: '-d 1'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '1004:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  front-tier:
    driver: overlay
